import { useMemo, useState } from "react";
import { Icon, Modal, PageHeader } from "../components";
import { useApp, type AcademicRecord } from "../app-context";
const institutions=["Tribhuvan University","Kathmandu University","Pokhara University","Purbanchal University","Mid-Western University","Far Western University","Nepal Sanskrit University","Lumbini Buddhist University","Rajarshi Janak University","Madan Bhandari University of Science and Technology","CTEVT","National Examinations Board","Other recognized institution"];
export default function EducationRecords(){
 const {academicRecords,addAcademicRecord,showToast}=useApp();const [query,setQuery]=useState("");const [open,setOpen]=useState(false);const [selected,setSelected]=useState<AcademicRecord|null>(null);
 const records=useMemo(()=>academicRecords.filter(r=>`${r.qualification} ${r.institution} ${r.registration}`.toLowerCase().includes(query.toLowerCase())),[academicRecords,query]);
 const sync=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const record:AcademicRecord={id:`AC-${Date.now()}`,qualification:String(f.get("qualification")),institution:String(f.get("institution")),level:String(f.get("level")),year:String(f.get("year")),registration:String(f.get("registration")),status:"Pending",credits:"Pending",division:"Pending verification"};addAcademicRecord(record);setOpen(false);showToast("Academic registry synchronization started")};
 return <div className="page education-page"><PageHeader eyebrow="NATIONAL ACADEMIC WALLET" title="Education records" copy="Degrees, diplomas, transcripts, and board certificates synchronized from recognized institutions across Nepal." action={<button className="button primary" onClick={()=>setOpen(true)}><Icon name="plus"/> Sync a qualification</button>}/>
 <section className="academic-hero"><div className="academic-seal">शिक्षा</div><div><p className="eyebrow">VERIFIED AT SOURCE</p><h2>One lifelong education profile</h2><p>Records are requested directly from the issuing university, board, or technical council. Each verified credential has a consent-based QR for instant validation.</p></div><dl><div><dt>Qualifications</dt><dd>{academicRecords.length}</dd></div><div><dt>Institutions</dt><dd>{new Set(academicRecords.map(r=>r.institution)).size}</dd></div></dl></section>
 <label className="catalog-search academic-search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search degree, university, or registration number"/><span>{records.length} records</span></label>
 <div className="academic-list">{records.map(r=><article className="academic-card" key={r.id}><div className="academic-card-head"><span className="university-mark">{r.institution.split(" ").map(x=>x[0]).join("").slice(0,3)}</span><div><small>{r.level.toUpperCase()} · {r.year}</small><h2>{r.qualification}</h2><p>{r.institution}</p></div><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span></div><div className="academic-meta"><div><span>Registration</span><b>{r.registration}</b></div><div><span>Result</span><b>{r.division}</b></div><div><span>Credits</span><b>{r.credits}</b></div></div><footer><span><Icon name="shield" size={18}/>{r.status==="Verified"?"Issuer signature valid":"Issuer response pending"}</span><button className="button secondary small" onClick={()=>setSelected(r)}>{r.status==="Verified"?"Open e-diploma":"View request"}</button></footer></article>)}</div>
 <section className="registry-strip"><div><Icon name="building"/><span><b>Institution-neutral by design</b><small>Federal universities, provincial universities, boards, academies, and CTEVT records use the same verified format.</small></span></div><div><Icon name="lock"/><span><b>Citizen-controlled sharing</b><small>Employers or institutions see a record only through an approved, expiring QR.</small></span></div></section>
 <Modal open={open} onClose={()=>setOpen(false)} title="Synchronize a qualification"><form onSubmit={sync}><div className="form-grid"><label className="span-2"><span>Issuing institution</span><select name="institution" required>{institutions.map(i=><option key={i}>{i}</option>)}</select></label><label><span>Qualification level</span><select name="level"><option>Certificate</option><option>Diploma</option><option>Bachelor</option><option>Master</option><option>MPhil</option><option>Doctorate</option></select></label><label><span>Completion year</span><input name="year" inputMode="numeric" required placeholder="2024"/></label><label className="span-2"><span>Degree, diploma, or certificate title</span><input name="qualification" required placeholder="As printed on the certificate"/></label><label className="span-2"><span>Registration or symbol number</span><input name="registration" required placeholder="Issuer registration number"/></label></div><p className="form-hint">The live platform would request the record from the selected institution. No scan is required when the issuing registry responds.</p><div className="modal-actions"><button type="button" className="button quiet" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary">Request synchronization</button></div></form></Modal>
 <Modal open={!!selected} onClose={()=>setSelected(null)} title="Verified electronic diploma">{selected&&<div className="diploma"><header><span className="brand-seal">न</span><div><small>GOVERNMENT OF NEPAL</small><b>National Academic Record</b></div><span className="university-mark">{selected.institution.split(" ").map(x=>x[0]).join("").slice(0,3)}</span></header><p>This certifies that</p><h2>Prabin Shrestha</h2><p>has completed the requirements for</p><h3>{selected.qualification}</h3><b>{selected.institution}</b><dl><div><dt>Registration</dt><dd>{selected.registration}</dd></div><div><dt>Completion</dt><dd>{selected.year}</dd></div><div><dt>Result</dt><dd>{selected.division}</dd></div></dl><div className="diploma-verify"><div className="qr-pattern" aria-label="Verification QR"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><span><b>Cryptographically verified</b><small>Scan to confirm issuer, holder consent, and current validity.</small></span></div><button className="button primary full" onClick={()=>showToast("Verified e-diploma downloaded")}><Icon name="download"/> Download e-diploma</button></div>}</Modal></div>}
