import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router";
import { Icon, Modal, ServiceGlyph } from "../components";
import { services, type Service } from "../data";
import { useApp } from "../app-context";

export default function ServiceDetail(){
 const {serviceId}=useParams();const service=services.find(s=>s.id===serviceId);const [apply,setApply]=useState(false);
 if(!service)return <div className="page empty-state"><h1>Service not found</h1><Link className="button primary" to="/services">Back to services</Link></div>;
 return <div className="page"><Link className="back-link" to="/services">← Service directory</Link>
  <section className="service-hero"><ServiceGlyph category={service.category}/><div><div className="service-tags"><span>{service.category}</span><span>{service.type}</span></div><h1>{service.name}</h1><p className="nepali large">{service.nepali}</p><p>{service.description}</p></div><button className="button primary" onClick={()=>setApply(true)}>Start application <Icon name="arrow" size={18}/></button></section>
  <div className="detail-layout"><div><section className="content-card"><p className="eyebrow">BEFORE YOU START</p><h2>What you will need</h2><ol className="requirement-list">{service.documents.map((d,i)=><li key={d}><span>{String(i+1).padStart(2,"0")}</span><div><b>{d}</b><small>Clear scan or photo · PDF, JPG or PNG</small></div></li>)}</ol></section><section className="content-card"><p className="eyebrow">HOW IT WORKS</p><h2>Simple, trackable process</h2><div className="process-row"><div><b>01</b><span>Complete form</span></div><div><b>02</b><span>Attach records</span></div><div><b>03</b><span>Agency review</span></div><div><b>04</b><span>Receive decision</span></div></div></section></div>
   <aside className="service-facts"><h3>Service details</h3><dl><div><dt>Responsible office</dt><dd>{service.agency}</dd></div><div><dt>Delivery</dt><dd>{service.type}</dd></div><div><dt>Estimated fee</dt><dd>{service.fee}</dd></div><div><dt>Typical time</dt><dd>{service.time}</dd></div></dl>{service.officialUrl&&<a className="official-link" href={service.officialUrl} target="_blank" rel="noreferrer"><span><b>Open official IRD website</b><small>ird.gov.np · Government of Nepal</small></span><Icon name="arrow" size={18}/></a>}<div className="secure-note"><Icon name="lock"/><p><b>Secure submission</b><br/>Your data is encrypted and shared only with the responsible office.</p></div></aside>
  </div><ApplicationFlow service={service} open={apply} onClose={()=>setApply(false)}/>
 </div>
}

function ApplicationFlow({service,open,onClose}:{service:Service;open:boolean;onClose:()=>void}){
 const [step,setStep]=useState(1);const [files,setFiles]=useState<string[]>([]);const [reference,setReference]=useState("");const {addApplication,showToast}=useApp();const nav=useNavigate();
 const submit=()=>{const ref=`${service.id.slice(0,3).toUpperCase()}-${Math.floor(100000+Math.random()*899999)}`;addApplication({id:`APP-${Date.now()}`,serviceId:service.id,name:service.name,nepali:service.nepali,date:"03 Sep 2026",status:"Submitted",progress:20,reference:ref});showToast("Application submitted successfully");onClose();nav("/activity")};
 return <Modal open={open} onClose={onClose} title={service.name} wide><div className="wizard-head">{["Applicant","Details","Documents","Review"].map((x,i)=><span className={step>=i+1?"active":""} key={x}><b>{i+1}</b>{x}</span>)}</div><div className="wizard-body">
  {step===1&&<div className="form-grid"><label><span>Full name</span><input defaultValue="Prabin Shrestha" required/></label><label><span>नाम (नेपालीमा)</span><input defaultValue="प्रबिन श्रेष्ठ" required/></label><label><span>National ID number</span><input defaultValue="983-472-810-5" required/></label><label><span>Mobile number</span><input defaultValue="+977 9841 234 567" required/></label><label className="span-2"><span>Permanent address</span><input defaultValue="Kathmandu Metropolitan City 10, Bagmati" required/></label></div>}
  {step===2&&<div className="form-grid"><label><span>Request purpose</span><select defaultValue="Personal"><option>Personal</option><option>Employment</option><option>Education</option><option>Travel</option><option>Business</option></select></label><label><span>Preferred district office</span><select><option>Kathmandu</option><option>Lalitpur</option><option>Bhaktapur</option><option>Kaski</option></select></label><label className="span-2"><span>Reference or account number</span><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Enter if available"/></label><label className="span-2"><span>Additional information</span><textarea rows={4} placeholder="Add information that will help the reviewing officer"/></label></div>}
  {step===3&&<div><div className="upload-zone"><Icon name="upload" size={30}/><h3>Attach supporting documents</h3><p>PDF, JPG, or PNG · maximum 10 MB each</p><label className="button secondary">Choose files<input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFiles(Array.from(e.target.files||[]).map(f=>f.name))}/></label></div><div className="file-list">{files.map(f=><div key={f}><Icon name="file"/><span><b>{f}</b><small>Ready to submit</small></span><button onClick={()=>setFiles(files.filter(x=>x!==f))}>Remove</button></div>)}</div>{files.length===0&&<p className="form-hint">You may continue without a file in this demonstration.</p>}</div>}
  {step===4&&<div className="review-box"><div className="review-person"><span><img src="/avatar.jpg" alt="Prabin Shrestha" /></span><div><b>Prabin Shrestha</b><small>NID 983-472-810-5 · Identity verified</small></div></div><dl><div><dt>Service</dt><dd>{service.name}</dd></div><div><dt>Office</dt><dd>{service.agency}</dd></div><div><dt>Documents</dt><dd>{files.length?`${files.length} attached`:"Demo submission"}</dd></div><div><dt>Fee</dt><dd>{service.fee}</dd></div></dl><label className="consent-check"><input type="checkbox" defaultChecked/><span>I confirm the information is correct and consent to sharing it with {service.agency}.</span></label></div>}
 </div><footer className="wizard-actions"><button className="button quiet" onClick={step===1?onClose:()=>setStep(step-1)}>{step===1?"Cancel":"Back"}</button><button className="button primary" onClick={step===4?submit:()=>setStep(step+1)}>{step===4?"Submit application":"Continue"}<Icon name="arrow" size={17}/></button></footer></Modal>
}
